### ISSUE TITLE
Generated ./sync/target/kubernetes/kubernetes.yml uses deprecated serviceAccount name

### ISSUE THREAD

**Issue by k-wall** [bf2fc6cc711aee1a0c2a/kas-fleetshard#547]
The generated deployments within the kubernetes.yml uses deprecated `serviceAccount` field rather than `serviceAccountName`.  Whilst functional this creates warnings from the tooling further down the pipelines.

```
          volumeMounts:
            - mountPath: /config
              name: logging-config-volume
              readOnly: false
      serviceAccount: kas-fleetshard-sync   # should be serviceAccountName
```

@shawkins is this the operator SDK?
