### ISSUE TITLE
Possible performance regression

### ISSUE THREAD

**Issue by shawkins** [bf2fc6cc711aee1a0c2a/kas-fleetshard#620]
There appears to be a performance regression in the throughput results in the low latency profile with no batching.

Running the instance profiler against 0.15 on 4.8 and earlier produce numbers similar to  

```
throughputResults:
  LATENCY_NO_BATCHING:
    averageMaxProducerMBs: 117.40602992350006
    averageMaxConsumerMBs: 117.40384791365771
    medianMaxProducerMBs: 117.31501737563312
    medianMaxConsumerMBs: 117.28390907546762
```

Running latest on 4.8 or 4.9 is capable of only about half that:

```
  LATENCY_NO_BATCHING:
    averageMaxProducerMBs: 59.26162430892092
    averageMaxConsumerMBs: 59.26106964325792
    medianMaxProducerMBs: 59.08476802526846
    medianMaxConsumerMBs: 59.09795303385282
```

Similarly latencies seem worse, but batching throughput seems the same.

This was evident after looking at https://issues.redhat.com/browse/MGDSTRM-6933 - my initial assumption was that the lower throughput was due to fewer resources, but not it appears due to other changes as well.
